# Generated by Django 5.0.6 on 2024-06-11 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apicore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapejob',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='scrapetask',
            name='updated_at',
        ),
    ]
