# Generated by Django 5.0.6 on 2024-06-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicore', '0002_remove_scrapejob_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapejob',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
